import numpy as np
import matplotlib.pyplot as plt
import random
import secrets
import pickle
import json

from os import listdir
       
if __name__ == "__main__":
    average_runs_conformity_DR_array = json.loads(open('average_runs_conformity_DR.json').read())
    average_runs_diversity_DR_array = json.loads(open('average_runs_diversity_DR.json').read())
    average_runs_conformity_lc1_DR_array = json.loads(open('average_conformity_lc1_DR.json').read())
    average_runs_conformity_lc2_DR_array = json.loads(open('average_conformity_lc2_DR.json').read())
    average_runs_conformity_lc3_DR_array = json.loads(open('average_conformity_lc3_DR.json').read())
    average_runs_conformity_lc4_DR_array = json.loads(open('average_conformity_lc4_DR.json').read())
    average_runs_conformity_lc5_DR_array = json.loads(open('average_conformity_lc5_DR.json').read())
    average_runs_conformity_lc6_DR_array = json.loads(open('average_conformity_lc6_DR.json').read())
    average_runs_conformity_lc7_DR_array = json.loads(open('average_conformity_lc7_DR.json').read())
    average_runs_conformity_lc8_DR_array = json.loads(open('average_conformity_lc8_DR.json').read())
    average_runs_conformity_lc9_DR_array = json.loads(open('average_conformity_lc9_DR.json').read())
    average_runs_conformity_lc10_DR_array = json.loads(open('average_conformity_lc10_DR.json').read())

    average_runs_norms1_frequency_lc1_DR_array = json.loads(open('average_runs_norms1_frequency_lc1_DR.json').read())
    average_runs_norms1_frequency_lc2_DR_array = json.loads(open('average_runs_norms1_frequency_lc2_DR.json').read())
    average_runs_norms1_frequency_lc3_DR_array = json.loads(open('average_runs_norms1_frequency_lc3_DR.json').read())
    average_runs_norms1_frequency_lc4_DR_array = json.loads(open('average_runs_norms1_frequency_lc4_DR.json').read())
    average_runs_norms1_frequency_lc5_DR_array = json.loads(open('average_runs_norms1_frequency_lc5_DR.json').read())
    average_runs_norms1_frequency_lc6_DR_array = json.loads(open('average_runs_norms1_frequency_lc6_DR.json').read())
    average_runs_norms1_frequency_lc7_DR_array = json.loads(open('average_runs_norms1_frequency_lc7_DR.json').read())
    average_runs_norms1_frequency_lc8_DR_array = json.loads(open('average_runs_norms1_frequency_lc8_DR.json').read())
    average_runs_norms1_frequency_lc9_DR_array = json.loads(open('average_runs_norms1_frequency_lc9_DR.json').read())
    average_runs_norms1_frequency_lc10_DR_array = json.loads(open('average_runs_norms1_frequency_lc10_DR.json').read())

    average_runs_norms2_frequency_lc1_DR_array = json.loads(open('average_runs_norms2_frequency_lc1_DR.json').read())
    average_runs_norms2_frequency_lc2_DR_array = json.loads(open('average_runs_norms2_frequency_lc2_DR.json').read())
    average_runs_norms2_frequency_lc3_DR_array = json.loads(open('average_runs_norms2_frequency_lc3_DR.json').read())
    average_runs_norms2_frequency_lc4_DR_array = json.loads(open('average_runs_norms2_frequency_lc4_DR.json').read())
    average_runs_norms2_frequency_lc5_DR_array = json.loads(open('average_runs_norms2_frequency_lc5_DR.json').read())
    average_runs_norms2_frequency_lc6_DR_array = json.loads(open('average_runs_norms2_frequency_lc6_DR.json').read())
    average_runs_norms2_frequency_lc7_DR_array = json.loads(open('average_runs_norms2_frequency_lc7_DR.json').read())
    average_runs_norms2_frequency_lc8_DR_array = json.loads(open('average_runs_norms2_frequency_lc8_DR.json').read())
    average_runs_norms2_frequency_lc9_DR_array = json.loads(open('average_runs_norms2_frequency_lc9_DR.json').read())
    average_runs_norms2_frequency_lc10_DR_array = json.loads(open('average_runs_norms2_frequency_lc10_DR.json').read())

    average_runs_norms3_frequency_lc1_DR_array = json.loads(open('average_runs_norms3_frequency_lc1_DR.json').read())
    average_runs_norms3_frequency_lc2_DR_array = json.loads(open('average_runs_norms3_frequency_lc2_DR.json').read())
    average_runs_norms3_frequency_lc3_DR_array = json.loads(open('average_runs_norms3_frequency_lc3_DR.json').read())
    average_runs_norms3_frequency_lc4_DR_array = json.loads(open('average_runs_norms3_frequency_lc4_DR.json').read())
    average_runs_norms3_frequency_lc5_DR_array = json.loads(open('average_runs_norms3_frequency_lc5_DR.json').read())
    average_runs_norms3_frequency_lc6_DR_array = json.loads(open('average_runs_norms3_frequency_lc6_DR.json').read())
    average_runs_norms3_frequency_lc7_DR_array = json.loads(open('average_runs_norms3_frequency_lc7_DR.json').read())
    average_runs_norms3_frequency_lc8_DR_array = json.loads(open('average_runs_norms3_frequency_lc8_DR.json').read())
    average_runs_norms3_frequency_lc9_DR_array = json.loads(open('average_runs_norms3_frequency_lc9_DR.json').read())
    average_runs_norms3_frequency_lc10_DR_array = json.loads(open('average_runs_norms3_frequency_lc10_DR.json').read())

    average_runs_norms4_frequency_lc1_DR_array = json.loads(open('average_runs_norms4_frequency_lc1_DR.json').read())
    average_runs_norms4_frequency_lc2_DR_array = json.loads(open('average_runs_norms4_frequency_lc2_DR.json').read())
    average_runs_norms4_frequency_lc3_DR_array = json.loads(open('average_runs_norms4_frequency_lc3_DR.json').read())
    average_runs_norms4_frequency_lc4_DR_array = json.loads(open('average_runs_norms4_frequency_lc4_DR.json').read())
    average_runs_norms4_frequency_lc5_DR_array = json.loads(open('average_runs_norms4_frequency_lc5_DR.json').read())
    average_runs_norms4_frequency_lc6_DR_array = json.loads(open('average_runs_norms4_frequency_lc6_DR.json').read())
    average_runs_norms4_frequency_lc7_DR_array = json.loads(open('average_runs_norms4_frequency_lc7_DR.json').read())
    average_runs_norms4_frequency_lc8_DR_array = json.loads(open('average_runs_norms4_frequency_lc8_DR.json').read())
    average_runs_norms4_frequency_lc9_DR_array = json.loads(open('average_runs_norms4_frequency_lc9_DR.json').read())
    average_runs_norms4_frequency_lc10_DR_array = json.loads(open('average_runs_norms4_frequency_lc10_DR.json').read())

    #print("average_runs_norms1_frequency_lc1_DR_array: ", average_runs_norms1_frequency_lc1_DR_array)
    #print("average_runs_norms2_frequency_lc1_DR_array: ", average_runs_norms2_frequency_lc1_DR_array)
    #print("average_runs_norms3_frequency_lc1_DR_array: ", average_runs_norms3_frequency_lc1_DR_array)
    #print("average_runs_norms4_frequency_lc1_DR_array: ", average_runs_norms4_frequency_lc1_DR_array)
          
    f, (ax1, ax2, ax3, ax4, ax5, ax6, ax7, ax8, ax9, ax10) = plt.subplots(10, sharex=True, sharey=True)
    ax1.plot(average_runs_norms1_frequency_lc1_DR_array, label = 'Norm 1 in lc1', linewidth=0.75, color = 'red')
    ax1.plot(average_runs_norms2_frequency_lc1_DR_array, label = 'Norm 2 in lc1', linewidth=0.75, color = 'green')
    ax1.plot(average_runs_norms3_frequency_lc1_DR_array, label = 'Norm 3 in lc1', linewidth=0.75, color = 'purple')
    ax1.plot(average_runs_norms4_frequency_lc1_DR_array, label = 'Norm 4 in lc1', linewidth=0.75, color = 'blue')

    ax2.plot(average_runs_norms1_frequency_lc2_DR_array, label = 'Norm 1 in lc2', linewidth=0.75, color = 'red')
    ax2.plot(average_runs_norms2_frequency_lc2_DR_array, label = 'Norm 2 in lc2', linewidth=0.75, color = 'green')
    ax2.plot(average_runs_norms3_frequency_lc2_DR_array, label = 'Norm 3 in lc2', linewidth=0.75, color = 'purple')
    ax2.plot(average_runs_norms4_frequency_lc2_DR_array, label = 'Norm 4 in lc2', linewidth=0.75, color = 'blue')

    ax3.plot(average_runs_norms1_frequency_lc3_DR_array, label = 'Norm 1 in lc3', linewidth=0.75, color = 'red')
    ax3.plot(average_runs_norms2_frequency_lc3_DR_array, label = 'Norm 2 in lc3', linewidth=0.75, color = 'green')
    ax3.plot(average_runs_norms3_frequency_lc3_DR_array, label = 'Norm 3 in lc3', linewidth=0.75, color = 'purple')
    ax3.plot(average_runs_norms4_frequency_lc3_DR_array, label = 'Norm 4 in lc3', linewidth=0.75, color = 'blue')

    ax4.plot(average_runs_norms1_frequency_lc4_DR_array, label = 'Norm 1 in lc4', linewidth=0.75, color = 'red')
    ax4.plot(average_runs_norms2_frequency_lc4_DR_array, label = 'Norm 2 in lc4', linewidth=0.75, color = 'green')
    ax4.plot(average_runs_norms3_frequency_lc4_DR_array, label = 'Norm 3 in lc4', linewidth=0.75, color = 'purple')
    ax4.plot(average_runs_norms4_frequency_lc4_DR_array, label = 'Norm 4 in lc4', linewidth=0.75, color = 'blue')

    ax5.plot(average_runs_norms1_frequency_lc5_DR_array, label = 'Norm 1 in lc5', linewidth=0.75, color = 'red')
    ax5.plot(average_runs_norms2_frequency_lc5_DR_array, label = 'Norm 2 in lc5', linewidth=0.75, color = 'green')
    ax5.plot(average_runs_norms3_frequency_lc5_DR_array, label = 'Norm 3 in lc5', linewidth=0.75, color = 'purple')
    ax5.plot(average_runs_norms4_frequency_lc5_DR_array, label = 'Norm 4 in lc5', linewidth=0.75, color = 'blue')

    ax6.plot(average_runs_norms1_frequency_lc6_DR_array, label = 'Norm 1 in lc6', linewidth=0.75, color = 'red')
    ax6.plot(average_runs_norms2_frequency_lc6_DR_array, label = 'Norm 2 in lc6', linewidth=0.75, color = 'green')
    ax6.plot(average_runs_norms3_frequency_lc6_DR_array, label = 'Norm 3 in lc6', linewidth=0.75, color = 'purple')
    ax6.plot(average_runs_norms4_frequency_lc6_DR_array, label = 'Norm 4 in lc6', linewidth=0.75, color = 'blue')

    ax7.plot(average_runs_norms1_frequency_lc7_DR_array, label = 'Norm 1 in lc7', linewidth=0.75, color = 'red')
    ax7.plot(average_runs_norms2_frequency_lc7_DR_array, label = 'Norm 2 in lc7', linewidth=0.75, color = 'green')
    ax7.plot(average_runs_norms3_frequency_lc7_DR_array, label = 'Norm 3 in lc7', linewidth=0.75, color = 'purple')
    ax7.plot(average_runs_norms4_frequency_lc7_DR_array, label = 'Norm 4 in lc7', linewidth=0.75, color = 'blue')

    ax8.plot(average_runs_norms1_frequency_lc8_DR_array, label = 'Norm 1 in lc8', linewidth=0.75, color = 'red')
    ax8.plot(average_runs_norms2_frequency_lc8_DR_array, label = 'Norm 2 in lc8', linewidth=0.75, color = 'green')
    ax8.plot(average_runs_norms3_frequency_lc8_DR_array, label = 'Norm 3 in lc8', linewidth=0.75, color = 'purple')
    ax8.plot(average_runs_norms4_frequency_lc8_DR_array, label = 'Norm 4 in lc8', linewidth=0.75, color = 'blue')

    ax9.plot(average_runs_norms1_frequency_lc9_DR_array, label = 'Norm 1 in lc9', linewidth=0.75, color = 'red')
    ax9.plot(average_runs_norms2_frequency_lc9_DR_array, label = 'Norm 2 in lc9', linewidth=0.75, color = 'green')
    ax9.plot(average_runs_norms3_frequency_lc9_DR_array, label = 'Norm 3 in lc9', linewidth=0.75, color = 'purple')
    ax9.plot(average_runs_norms4_frequency_lc9_DR_array, label = 'Norm 4 in lc9', linewidth=0.75, color = 'blue')

    ax10.plot(average_runs_norms1_frequency_lc10_DR_array, label = 'Norm 1 in lc10', linewidth=0.75, color = 'red')
    ax10.plot(average_runs_norms2_frequency_lc10_DR_array, label = 'Norm 2 in lc10', linewidth=0.75, color = 'green')
    ax10.plot(average_runs_norms3_frequency_lc10_DR_array, label = 'Norm 3 in lc10', linewidth=0.75, color = 'purple')
    ax10.plot(average_runs_norms4_frequency_lc10_DR_array, label = 'Norm 4 in lc10', linewidth=0.75, color = 'blue')

    #plt.gca().legend(loc='center left', bbox_to_anchor=(1, 0.5))
    #plt.show()
    #ax10.legend(bbox_to_anchor=(1.05, 1), loc='upper left', borderaxespad=0.)

    ax1.legend(loc = 'upper right', fontsize = 8)
    ax2.legend(loc = 'upper right', fontsize = 8)
    ax3.legend(loc = 'upper right', fontsize = 8)
    ax4.legend(loc = 'upper right', fontsize = 8)
    ax5.legend(loc = 'upper right', fontsize = 8)
    ax6.legend(loc = 'upper right', fontsize = 8)
    ax7.legend(loc = 'upper right', fontsize = 8)
    ax8.legend(loc = 'upper right', fontsize = 8)
    ax9.legend(loc = 'upper right', fontsize = 8)
    ax10.legend(loc = 'upper right', fontsize = 8)

    ax1.grid(True)
    ax2.grid(True)
    ax3.grid(True)
    ax4.grid(True)
    ax5.grid(True)
    ax6.grid(True)
    ax7.grid(True)
    ax8.grid(True)
    ax9.grid(True)
    ax10.grid(True)

    ax1.set_title('Frequence of Norm Emergence (Average in 100 Runs)', fontsize=20)
    ax10.set_xlabel('Iterations', fontsize=15)
    ax5.set_ylabel('Frequence', fontsize=15)
    f.subplots_adjust(hspace=0)
    plt.setp([a.get_xticklabels() for a in f.axes[:-1]], visible=False)
    plt.show()

    #average_runs_totalrewards_dynamicrewards_array = json.loads(open('average_runs_dynamicrewards_totalrewards.json').read())
    #print ("average_runs_conformity_array: ", average_runs_conformity_array)
    #print ("average_runs_totalrewards: ", average_runs_totalrewards_array)

    #print (average_runs_totalrewards_dynamicrewards_array)

# Plotting performance using graphs =>    
    plt.figure()
    plt.plot(average_runs_conformity_DR_array, label = 'Conformity', color = 'red')
    plt.ylim(ymin=0)
    #pickle.dump(average_runs_conformity_array, open("numberofactions-10.pickle", "wb")) 
    plt.xlabel("Iterations", fontsize=15)
    plt.ylabel("Conformity", fontsize=15)
    plt.title("Effects of Dynamic Payoff on Conformity (average of all communities)", fontsize=20)
    plt.legend()
    plt.grid(True)
    plt.show()

    number_of_iterations = 2000
    p = np.arange(0, number_of_iterations, 1)
    f, (ax1, ax2, ax3, ax4, ax5, ax6, ax7, ax8, ax9, ax10) = plt.subplots(10, sharex=True, sharey=True)
    ax1.plot(p, average_runs_conformity_lc1_DR_array, label = 'Conformity - local community #1', color='green')
    plt.ylim(ymin=0)
    ax2.plot(p, average_runs_conformity_lc2_DR_array, label = 'Conformity - local community #2', color='red')
    plt.ylim(ymin=0)
    ax3.plot(p, average_runs_conformity_lc3_DR_array, label = 'Conformity - local community #3', color='blue')
    plt.ylim(ymin=0)
    ax4.plot(p, average_runs_conformity_lc4_DR_array, label = 'Conformity - local community #4', color='orange')
    plt.ylim(ymin=0)
    ax5.plot(p, average_runs_conformity_lc5_DR_array, label = 'Conformity - local community #5', color='pink')
    plt.ylim(ymin=0)
    ax6.plot(p, average_runs_conformity_lc6_DR_array, label = 'Conformity - local community #6', color='brown')
    plt.ylim(ymin=0)
    ax7.plot(p, average_runs_conformity_lc7_DR_array, label = 'Conformity - local community #7', color='purple')
    plt.ylim(ymin=0)
    ax8.plot(p, average_runs_conformity_lc8_DR_array, label = 'Conformity - local community #8', color='black')
    plt.ylim(ymin=0)
    ax9.plot(p, average_runs_conformity_lc9_DR_array, label = 'Conformity - local community #9', color='silver')
    plt.ylim(ymin=0)
    ax10.plot(p, average_runs_conformity_lc10_DR_array, label = 'Conformity - local community #10', color='yellow')
    plt.ylim(ymin=0)
    ax1.legend()
    ax2.legend()
    ax3.legend()
    ax4.legend()
    ax5.legend()
    ax6.legend()
    ax7.legend()
    ax8.legend()
    ax9.legend()
    ax10.legend()
    ax1.grid(True)
    ax2.grid(True)
    ax3.grid(True)
    ax4.grid(True)
    ax5.grid(True)
    ax6.grid(True)
    ax7.grid(True)
    ax8.grid(True)
    ax9.grid(True)
    ax10.grid(True)
    ax1.set_title('Plotting Individual Conformity of all Local Communities (Average in 100 runs)', fontsize=20)
    ax9.set_xlabel('Iterations', fontsize=15)
    ax4.set_ylabel('Conformity', fontsize=15)
    f.subplots_adjust(hspace=0)
    plt.setp([a.get_xticklabels() for a in f.axes[:-1]], visible=False)
    plt.show()


    plt.figure()
    plt.plot(average_runs_diversity_DR_array, label = 'Diversity', color = 'green')
    plt.ylim(ymin=0)
    #pickle.dump(average_runs_conformity_array, open("numberofactions-10.pickle", "wb")) 
    plt.xlabel("Iterations", fontsize=15)
    plt.ylabel("Diversity", fontsize=15)
    plt.title("Effects of Dynamic Payoff on Diversity", fontsize=20)
    plt.legend()
    plt.grid(True)
    plt.show()


##    plt.figure()
##    plt.plot(average_runs_totalrewards_dynamicrewards_array, label = 'Q-Learning', color = 'green')
##    #plt.ylim(ymin=0)
##    plt.xlabel("Iterations", fontsize=15)
##    plt.ylabel("Total Payoff", fontsize=15)
##    plt.title("Effects of Dynamic Payoff on Total Payoff", fontsize=20)
##    plt.legend()
##    plt.grid(True)
##    plt.show()
